version: "3"

services:
    postgres:
        image: postgres
        environment:
            POSTGRES_PASSWORD: "admin"
        ports:
            - "5432:5432"
        networks:
            - postgres-network

    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: "admin@gmail.com"
            PGADMIN_DEFAULT_PASSWORD: "admin"
        ports:
            - "5433:80"
        depends_on:
            - postgres
        networks:
            - postgres-network

networks:
    postgres-network:
        driver: bridge
